### ISSUE TITLE
Introduce method to seamlessly integrate new maps

### ISSUE THREAD

**Issue by william-eiers** [UCSB-CS56-Projects/cs56-games-pokemon-map#15]
Add new classes/utilities within the project in order to seamlessly introduce new map and textures. Currently, it is quite difficult to simply add another map, which is an integral part of the game. 
(750 points)

**Comment by alecharrell** [comment]
Approved: A.H.

**Comment by shunjizhan** [comment]
We added many new methods so that we could put a building in the map on any particular coordinate.We could build a new class and put all methods to create building in there, but finally we decided to just put it in the Renderer class.

we now have methods to create:
pokeball, pokecenter,  pokemart, small house, tree, medium house, large house, big fish, door, big building1, big building2, big rock, lake, small rock, flower1, flower2, nice tree, big pokemon1, big pokemon 2.
